spring.application.name=plsql-ai-cli

# 1) Do NOT start as web application
spring.main.web-application-type=none

# 2) Enable Spring Shell REPL
spring.shell.interactive.enabled=true

# 3) Reduce JLine noise
logging.level.org.jline=INFO

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
#codellama:13b
spring.ai.ollama.chat.options.model=qwen3-coder:30b
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.top-p=0.9
