spring.application.name=plsql-ai-cli

# 1) Do NOT start as web application
spring.main.web-application-type=none

# 2) Enable Spring Shell REPL
spring.shell.interactive.enabled=true

# Ollama Configuration (see at OllamaConfig.java)
spring.ai.ollama.base-url=http://localhost:11434

